apps/datban/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template


urlpatterns = patterns('',
	#url(r'^$', direct_to_template, { 'template': 'datban/datbanhome.html', }, name = 'home'),
	url(r'^$', "datban.views.home" , name = "home"),
	url(r'^lands/(?P<unit_path>.*?)/$', "datban.views.lands", name = "lands"),
	url(r'^bando/(?P<unit_path>.*?)$', "datban.views.map", name = "map"),
	# Web services
	url(r'^coordtrans/$', "datban.views.coordtrans", name = "coordtrans"),
	url(r'^reversecoordtrans/$', "datban.views.reversecoordtrans", name = "reversecoordtrans"),
	url(r'^landws/$', "datban.views.landws", name = "landws"),
	url(r'^land_info/$', "datban.views.land_info", name = "land_info"),
	url(r'^test$', direct_to_template , {'template': 'datban/test.html'}),
	url(r'^edit/$', 'datban.views.land_edit', name='land_edit'),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template, redirect_to


from django.contrib import admin
admin.autodiscover()

from microblogging.feeds import TweetFeedAll, TweetFeedUser, TweetFeedUserWithFriends
from microblogging.models import Tweet
from tagging.models import TaggedItem

from pinax.apps.account.openid_consumer import PinaxConsumer
from pinax.apps.blog.feeds import BlogFeedAll, BlogFeedUser
from pinax.apps.blog.models import Post


handler500 = "pinax.views.server_error"


tweets_feed_dict = {"feed_dict": {
    "all": TweetFeedAll,
    "only": TweetFeedUser,
    "with_friends": TweetFeedUserWithFriends,
}}

blogs_feed_dict = {"feed_dict": {
    "all": BlogFeedAll,
    "only": BlogFeedUser,
}}

urlpatterns = patterns("",
	url(r'^$', redirect_to, {"url": "/datban/",	"permanent": True, }, name="home_root"),	
	(r'^datban/', include ('datban.urls')), #urls for datban app
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^about/", include("about.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/(.*)", PinaxConsumer()),
    url(r"^profiles/", include("profiles.urls")),
    url(r"^bbauth/", include("pinax.apps.bbauth.urls")),
    url(r"^authsub/", include("pinax.apps.authsub.urls")),
    url(r"^blog/", include("pinax.apps.blog.urls")),
    url(r"^invitations/", include("friends_app.urls")),
    url(r"^notices/", include("notification.urls")),
    url(r"^messages/", include("messages.urls")),
    url(r"^announcements/", include("announcements.urls")),
    url(r"^tweets/", include("microblogging.urls")),
    url(r"^comments/", include("threadedcomments.urls")),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^avatar/", include("avatar.urls")),
    url(r"^flag/", include("flag.urls")),
    url(r"^feeds/tweets/(.*)/$", "django.contrib.syndication.views.feed", tweets_feed_dict),
    url(r"^feeds/posts/(.*)/$", "django.contrib.syndication.views.feed", blogs_feed_dict),
)

## @@@ for now, we'll use friends_app to glue this stuff together

friends_blogs_kwargs = {
    "template_name": "blog/friends_posts.html",
    "friends_objects_function": lambda users: Post.objects.filter(author__in=users),
}

friends_tweets_kwargs = {
    "template_name": "microblogging/friends_tweets.html",
    "friends_objects_function": lambda users: Tweet.objects.filter(sender_id__in=[user.id for user in users], sender_type__name="user"),
}

urlpatterns += patterns("",
    url(r"^blog/friends_blogs/$", "friends_app.views.friends_objects", kwargs=friends_blogs_kwargs, name="friends_blogs"),
    url(r"^tweets/friends_tweets/$", "friends_app.views.friends_objects", kwargs=friends_tweets_kwargs, name="friends_tweets"),
)

tagged_models = (
    dict(title="Blog Posts",
        query=lambda tag : TaggedItem.objects.get_by_model(Post, tag).filter(status=2),
        content_template="pinax_tagging_ext/blogs.html",
    ),
)
tagging_ext_kwargs = {
    "tagged_models": tagged_models,
}

urlpatterns += patterns("",
    url(r"^tags/(?P<tag>.+)/(?P<model>.+)$", "tagging_ext.views.tag_by_model",
        kwargs=tagging_ext_kwargs, name="tagging_ext_tag_by_model"),
    url(r"^tags/(?P<tag>.+)/$", "tagging_ext.views.tag",
        kwargs=tagging_ext_kwargs, name="tagging_ext_tag"),
    url(r"^tags/$", "tagging_ext.views.index", name="tagging_ext_index"),
)

if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

apps/datban/models.py
# -*- coding: utf-8 -*-
from django.contrib.gis.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
import datetime, os, re, traceback
from django.core.urlresolvers import reverse
from django.contrib.gis.maps.google.overlays import GPolyline
from utils import encode
from django.db import transaction

ID_GAP = 1000000


#from django.core.management.validation import max_length
#from twisted.python.util import blank
#from django.contrib.admin.util import limit_choices_to, related_name

from datban import utils


class AdminUnit (models.Model):
    
	LEVEL_CHOICES = (
		(1, _('Coutry')),
		(2, _('Province')),
		(3, _('District')),
		(4, _('Ward')),
	)
    
	name = models.CharField(_('Name'), max_length = 50)
	geometry = models.MultiPolygonField(_('Geographic Border'),srid=4326)
	level = models.IntegerField( choices = LEVEL_CHOICES, default = 2) #province, district, ward
	superordinate = models.ForeignKey('self', blank = True, null = True, related_name = 'subordinates')
	slug = models.CharField(_('Slug'), max_length=50)
	path = models.CharField(_('Unit Path'), max_length=100, blank = True)
	markup = models.CharField( _('Http Markup'), max_length = 500, blank = True)
	objects = models.GeoManager()
	sub_order = models.IntegerField(_('Order'))
	class Meta:
		ordering = ['sub_order', 'name']
		
	def __unicode__(self):
		unit = self
		names = list()
		while unit and unit.level > 1: 
			names.append(unit.name)
			unit = unit.superordinate
		return os.path.sep.join(names)
	
	def save(self, *args, **kwargs):
		''' On save, Unit Path and Http Markup '''
		
		#Create list of superordinate
		supers = list()
		slugs = list()
		unit = self
		#Auto generate slug if not set
		if not unit.slug or not unit.slug.strip():
			unit.slug = re.sub(r'\s', '', utils.remove_accent(unit.name.encode('utf8')).lower())
		#Select all super except Vietnam
		while unit and unit.level > 1: 
			supers.append(unit)
			slugs.append(unit.slug)
			unit = unit.superordinate
		supers.reverse()
		slugs.reverse()		
		self.path = os.path.sep.join(slugs)
        
		links = list()         
		for unit in supers:
			url = reverse('lands',  args = [unit.path])
			link = u'<a href="%s">%s</a>' % (url, unit.name)
			links.append(link)
		self.markup = os.path.sep.join(links)	
		super(AdminUnit, self).save(*args, **kwargs)


class Land (models.Model):
    
	LEGAL_STATUS_CHOICES = (
		(1, _('Red Paper')),
		(2, _('Pink Paper')),
		(3, _('Hand Written Paper')),
	)
	
	LAND_TYPE_CHOICES = (
		(1, _('Residence')),
		(2, _('House')),
		(3, _('Agricultural')),
		(4, _('Agricultural + Residence')),
	)
	
	LISTING_STATUS_CHOICES = (
		(1, _('For Sales')),
		(2, _('Need To Buy')),
		(3, _('Sold')),
	)
	user = models.ForeignKey(User, verbose_name=_('user'))
	geometry = models.MultiPolygonField(_('Land Border'),srid=4326)
	price = models.BigIntegerField(_('Listed Price'), blank = True, null = True) #unit: million VND
	area = models.FloatField(_('Total Area (m2)')) #unit: m2 (square meter)
	legal_status = models.IntegerField(_('Legal Status'), choices = LEGAL_STATUS_CHOICES, default = 1) # Sổ Đỏ, Sổ Hồng, Giấy Tay
	land_type = models.IntegerField(_('Land Type'), choices = LAND_TYPE_CHOICES, default = 1)# Nhà Ở, Thổ Cư, Nông Nghiệp, Nông Nghiệp + Thổ Cư
	marker = models.PointField(_('Position'), srid=4326, blank = True, null = True)
	owner_name = models.CharField(_("Owner's Name"), max_length = 50, blank = True)
	admin_unit = models.ForeignKey(AdminUnit, verbose_name = _('Administrative Unit'), blank = True, null= True)
	listing_status = models.IntegerField(_('Listing Status'), choices = LISTING_STATUS_CHOICES, default = 1)  #selling, buing, sold
	created_on = models.DateTimeField(_('Created On'), blank = True)
	last_modified = models.DateTimeField(_('Last Modified'), blank = True)
	description = models.TextField(_('Description'))
	contact_phone = models.CharField(_('Contact Phone'), max_length = 20)
	contact_name =  models.CharField(_('Contact Name'), max_length = 50)
	static_map = models.URLField(_('Static Map'), max_length = 2000, blank = True)
	objects = models.GeoManager()
	is_private = models.BooleanField(_('Private Listing'), default = False)
	
	class Meta:
		ordering = ['-last_modified']	
		
    ## Generate static google map from multipolygon url
    #  @example http://maps.googleapis.com/maps/api/staticmap?path=color:0xff0000ff|weight:5|40.737102,-73.990318|40.749825,-73.987963|40.752946,-73.987384|40.755823,-73.986397&size=512x512&sensor=false
	def generate_static_map(self):
		if self.geometry is None:
			return None
		# The Geometry's WKT will look like this MULTIPOLYGON (((106.6786154212305036 10.6854475768920061, 106.6789901199219770 10.6854283820627280, 106.6788799962620260 10.6852840635758657, 106.6785783928939253 10.6852940006168762, 106.6786154212305036 10.6854475768920061)))
		import re
		self.geometry.transform(4326)
		matches = re.findall('(\([\d\s\,\.]*\))', self.geometry.wkt)
		polylines = list()
		for match in matches:
			#Convert WKT to google stuff
			 vertices = re.findall( '(?P<x>\d+\.\d+)\s+(?P<y>\d+\.\d+)' , match.strip('()') )
			 ll_list = list()
			 for vertex in vertices:
			 	#x is lon, y is lat
			 	ll_list.append('%s,%s' % (vertex[1], vertex[0]))
			 polyline = 'path=color:0xff8300ff|%s' % ( '|'.join(ll_list), )
			 polylines.append(polyline)
		#http://maps.googleapis.com/maps/api/staticmap?maptype=satellite&size=160x160&sensor=false&path=color:0xff8300ff|10.6854475768919279,106.6786154212305178|10.6854283820627138,106.6789901199219486|10.6852840635758000,106.6788799962619976|10.6852940006168620,106.6785783928939537|10.6854475768919279,106.6786154212305178	 
		url = 'http://maps.googleapis.com/maps/api/staticmap?maptype=satellite&size=160x160&sensor=false&%s' % ( '&'.join(polylines), )
		return url
	
	def get_admin_unit(self):
		ou = AdminUnit.objects.filter(geometry__intersects=self.geometry)
		max_level =0
		max_area=0
		max = None
		for u in ou:
			g =  self.geometry.intersection(u.geometry)
			g.transform(900913)
			if (u.level == max_level and g.area > max_area) or u.level > max_level:
				max_level = u.level
				max_area = g.area
				max=u
		return max
	
	def full_map_url(self):
		return '/datban/bando/%s?%s' % (self.admin_unit.path, encode(self.id + ID_GAP))
	
	def save(self, *args, **kwargs):
		''' On save, update timestamps '''
		if not self.id:
		    self.created_on = datetime.datetime.today()
		if not kwargs.get('keep_date'):
			self.last_modified = datetime.datetime.today()
		self.static_map = self.generate_static_map()
		self.admin_unit = self.get_admin_unit()
		super(Land, self).save()

	def gpoly(self):
		gpoly = GPolyline(self.geometry[0])
		return gpoly.latlngs.replace('GLatLng', 'google.maps.LatLng')
	
class Invitation(models.Model):
	'An invitation keeps a ticket which will be expired after a specific hours (default is 24 hours)'
	ticket = models.CharField(max_length = 20, blank = False)
	expired_after = models.IntegerField(_('Expired After'), default = 24)
	created_on = models.DateTimeField(_('Created On'), auto_now_add = True, blank = True)
	land = models.ForeignKey(Land, verbose_name = _('Land'), blank = False)	
	
class ThuaDiaChinh(models.Model):
	wkb_geometry = models.GeometryField(srid=4326)
	idthua = models.CharField(max_length = 10, blank = True)
	soto = models.CharField(max_length = 20, blank = True)
	sothua = models.CharField(max_length = 20, blank = True)
	dientich = models.FloatField(blank = True)
	tennha = models.CharField(max_length = 100, blank = True)
	tenchusohuu = models.CharField(max_length = 100, blank = True)
	sonha = models.CharField(max_length = 50, blank = True)
	sonhamoi = models.CharField(max_length = 50, blank = True)
	maduong = models.CharField(max_length = 20, blank = True)
	maduongmoi = models.CharField(max_length = 20, blank = True)
	maphuong = models.CharField(max_length = 7, blank = True)
	maquan = models.CharField(max_length = 5, blank = True)
	idconduong = models.CharField(max_length = 10, blank = True)
	tenconduong = models.CharField(max_length = 100, blank = True)
	objects = models.GeoManager()	

class HcmDistrict(models.Model):
	code = models.CharField(max_length=12)
	name = models.CharField(max_length=50)
	geometry = models.GeometryField(srid=4326)
	objects = models.GeoManager()

class HcmWard(models.Model):
	code = models.CharField(max_length=12)
	name = models.CharField(max_length=50)
	geometry = models.GeometryField(srid=4326)
	district_code = models.CharField(max_length=50)
	objects = models.GeoManager()
	
	
	
	
	
	

apps/profiles/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from datban.models import AdminUnit

from timezones.fields import TimeZoneField

class Profile(models.Model):
    
    user = models.ForeignKey(User, unique=True, verbose_name=_('user'))
    name = models.CharField(_('name'), max_length=50, null=True, blank=True)
    about = models.TextField(_('about'), null=True, blank=True)
    location = models.CharField(_('location'), max_length=40, null=True, blank=True)
    website = models.URLField(_('website'), null=True, blank=True, verify_exists=False)
    admin_unit = models.ManyToManyField(AdminUnit, blank = True, null = True)
    def __unicode__(self):
        return self.user.username
    
    def get_absolute_url(self):
        return ('profile_detail', None, {'username': self.user.username})
    get_absolute_url = models.permalink(get_absolute_url)
    
    class Meta:
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')

def create_profile(sender, instance=None, **kwargs):
    if instance is None:
        return
    profile, created = Profile.objects.get_or_create(user=instance)

post_save.connect(create_profile, sender=User)

apps/datban/forms.py
from django import forms
from datban.models import Land

class LandFormStaff(forms.ModelForm):
    class Meta:
        model = Land
        exclude = ('geometry', 'marker', 'admin_unit', 'created_on', 'last_modified', 'static_map')

class LandForm(forms.ModelForm):
    class Meta:
        model = Land
        exclude = ('user', 'geometry', 'marker', 'admin_unit', 'created_on', 'last_modified', 'static_map')

templates/datban/datbanhome.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}
{% load avatar_tags %}
{% block head_title %}{% trans "Home" %}{% endblock %}

{% block body %}

<div id="content">
    <div id="leftpanel">
        <div id="vietnammap">
        	<a id="hotspot" href="/datban/lands/thanhphohochiminh"></a>
			<img src="{{ STATIC_URL }}images/vietnammap.jpg" alt="Bản Đồ"/>
		</div>
    </div><!-- LEFT PANEL -->
    <div id="rightpanel">
        <div id="citytable" >
        	<ul class="objectlist">
        		<li><h3>{% trans "Provinces - Cities" %}</h3></li>
        		<li class="odd"><a href="/datban/lands/thanhphohochiminh">Tp. Hồ Chí Minh</a></li>
        		<li class="even"><a href="#">Cần Thơ</a></li>
        	</ul>
        </div><!-- CITY TABLE -->
        <br/>
        <div id="consultanttable">
        	<ul class="objectlist">
        		<li><h3>{% trans "Registered Consultants" %}</h3></li>
        		{% for user in users %}
		    		<li class="{% cycle 'odd' 'even' %}">
		    			<a  href="{% url profile_detail user.username %}">
		    				<div style="float:left; margin: -12px 10px 0px -0.9em;"> {% avatar user 40 %}</div>
		    				{% if user.get_profile.name %}
		    					{{ user.get_profile.name }}
		    				{% else %}
		    					{{ user.username }}
		    				{% endif %}
		    			</a>
		    		</li>
	            {% endfor %}
        	</ul>
        </div><!-- CONSULTANT TABLE -->
        
    </div><!-- RIGHT PANEL -->
    <br style="clear:both;"/>
</div><!-- CONTENT -->
</div>

{% endblock %} <!-- BLOCK BODY -->

templates/datban/land_edit_facebox.html
{% load uni_form_tags %}
{% load i18n %}
{% load datban_tags %}
<script type="text/javascript">
	$(function() {
		var form = $("#land_form");
		form.submit(function() {
			$("#sendbutton").attr('disabled', true);
			$("#sendwrapper").prepend('<span>Sending message, please wait... </span>');
			$("#ajaxwrapper").load(
				"{% url_land_edit land last_page %}", 
				form.serializeArray(), function(responseText, responseStatus, xhr) {
					var ct = xhr.getResponseHeader("content-type") || "";
					if (ct == 'text/plain') {
						window.location.replace(responseText);
					};
					$("#sendbutton").attr('disabled', false)
				});
			return false;
		});
	});
</script>
<h1>{% trans "Edit Land" %}</h1>
<div id="ajaxwrapper">
	<form class="uniForm" method="POST" id="land_form" {% url_land_edit land last_page %}>
	
		<fieldset>
			{{ land_form|as_uni_form }}
			<div class="form_block">
				<p id="sendwrapper">
					<input type="submit" value="{% trans "Update" %}" id="sendbutton"/>
				</p>
			</div>
		</fieldset>
	
	</form>
</div>

templates/datban/land_info.html
{% load i18n %}
{% load humanize %}
{% load datban_tags %}
<table summary="{% trans "Property details" %}" class="propertydetail">
	{% if land.is_private %}
	<tr>
		<td><span class="private-button">Private</span></td>
	</tr>
	{% endif %}
	<tr>
		<th>{% trans "Local" %}</th>
		<td>{{ land.admin_unit.markup|safe }}</td>
	</tr>
	<tr>
		<th>{% trans "Land type" %}</th>
		<td>{% trans land.get_land_type_display %}</td>
	</tr>
	{% if land.owner_name %}
		<tr>
			<th>{% trans "Owner" %}</th>
			<td>{{ land.owner_name }}</td>
		</tr>
	{% endif %}
	<tr>
		<th>{% trans "Listing status" %}</th>
		<td>{{ land.get_listing_status_display }}{% if land.user == user or user.is_staff %} / <a href="#" id="land_edit" >{% trans "Update information" %}</a> {% endif %}</td>
	</tr>
	<tr>
		<th>{% trans "Area" %}</th>
		<td>{{ land.area|floatformat }} m<sup>2</sup></td>
	</tr>
	<tr>
		<th>{% trans "Price" %}</th>
		<td>{% if land.price == 0 %}{% trans "Negotiable" %}{% else %}{{ land.price|intword }} Đồng{% endif %}</td>
	</tr>
	<tr>
		<th>{% trans  "Posted by" %}</th>
		<td><a href="{% url profile_detail land.user.username %}">
			{% if land.user.get_profile.name %}
				{{ land.user.get_profile.name }}
			{% else %}
				{{ land.user.username }}
			{% endif %}
		</a></td>
	</tr>
	<tr>
		<th>{% trans "Contact" %}</th>
		<td>{{ land.contact_name }} - {{ land.contact_phone }}</td>
	</tr>
</table>
<script type="text/javascript">
	$("#land_edit").click(function(){
		jQuery.facebox({ ajax: '{% url_land_edit land last_page %}' });
	});
</script>

templates/datban/lands.html
{% extends "site_base.html" %}
{% load i18n %}
{% load humanize %}
{% load datban_tags %}
{% load avatar_tags %}
{% load pagination_tags %}

{% block head_title %}{% trans "Home" %}{% endblock %}

{% block subnav %}
	<div id = "breadcrumb">
			>>>>  {{ unit.markup|safe }}
	</div>
{% endblock %}

{% block body %}

<div id="content">
    <div id="leftpanel">
		<div id="sort-bar">
			<form method="get" class="inline-form">
				<input type="submit" class="sort-button {% if sort == "listed" %}active{% endif %}" value="{% trans "Listed" %}" />
				<input type="hidden" name="sort" value="listed"/>
			</form>
			<form class="inline-form">
				<input type="submit" class="sort-button {% if sort == "sold" %}active{% endif %}" value="{% trans "Sold" %}" />
				<input type="hidden" name="sort" value="sold" />
			</form>
			<form class="inline-form">
				<input type="submit" class="sort-button {% if sort == "all" %}active{% endif %}" value="{% trans "All" %}" />
				<input type="hidden" name="sort" value="all" />
			</form>
		</div>
    	<div id="propertytable">
    		<h3> 
    			{% if sort == "listed" %}{% trans "Lands currently listed in " %}{% endif %}
    			{% if sort == "sold" %}{% trans "Lands sold in " %}{% endif %}
    			{% if sort == "all" %}{% trans "All lands sold or currently listed in " %}{% endif %}
    			{{ unit.name }}
    		</h3>
			<br/><br/>
    		{% if lands %}
    			{% autopaginate lands %}    			
    			<ul class="propertylist">
	    		   	{% for land in lands %}
		        		<li>
		        			<a href="{{ land.full_map_url }}"><img src="{{ land.static_map }}" alt="{% trans "Land Map" %}" class="mappreview"/></a>
		        			{% land_info %}
		        			<br style="clear: both;"/>
		        		</li>
	        		{% endfor %}
	        	</ul>
	        	{% paginate %}
        	{% else %}
				<span> {% trans "No lands found" %}</span>
			{% endif %}        		
    	</div> <!-- PROPERTY TABLE -->
	</div><!-- LEFT PANEL -->
    <div id="rightpanel">
        <div id="citytable" >
        	<ul class="objectlist">
        		{% if unit.subordinates.all %} <!-- SELECT SUBs, ELSE SELECT PEERs -->
        			{% for subordinate in unit.subordinates.all %}
			        	{% if forloop.first %}
	        				<li><h3>{{ subordinate.get_level_display }}</h3></li>
	        			{% endif %}
	        			<li class="{% cycle 'odd' 'even' %}">
	        				<a href="{% url lands subordinate.path %}">{{ subordinate.name }}</a>
	        			</li>
	        		{% endfor %}
	        	{% else %}
	        		{% for peer in unit.superordinate.subordinates.all %}
	        			{% if forloop.first %}
	        				<li><h3>{{ unit.get_level_display }}</h3></li>
	        			{% endif %}
 		       			<li class="{% cycle 'odd' 'even' %}">
	        				<a href="{% url lands peer.path %}">{{ peer.name }}</a>
	        			</li>
	        		{% endfor %}
	        	{% endif %}
        	</ul>
        </div><!-- CITY TABLE -->
        <br/>
        <div id="consultanttable">
        	<ul class="objectlist">
        		<li><h3>{% trans "Registered Consultants" %}</h3></li>
        		{% for profile in unit.profile_set.all %}
		    		<li class="{% cycle 'odd' 'even' %}">
		    			<a  href="{% url profile_detail profile %}">
		    				<div style="float:left; margin: -12px 10px 0px -0.9em;"> {% avatar profile.user 40 %}</div>
		    				{% if profile.name %}
		    					{{ profile.name }}
		    				{% else %}
		    					{{ profile.user.username }}
		    				{% endif %}
		    			</a>
		    		</li>
	            {% endfor %}
        	</ul>
        </div><!-- CONSULTANT TABLE -->
        
    </div><!-- RIGHT PANEL -->
    <br style="clear:both;"/>
</div><!-- CONTENT -->
</div>

{% endblock %} <!-- BLOCK BODY -->

templates/datban/m_home.html
{% extends "datban/m_base.html" %}
{% load i18n %}

{% block head_title %}Xem Đất Bán{% endblock %}


{% block leftbutton %}
	{% if user.is_authenticated %}
		<a id="homeButton" class="button" href="{% url profile_detail user %}">{% trans "My Lands" %}</a>
	{% endif %}	
{% endblock %}


{% block body %}
	<div  selected="true">
		<br/>
	    <a href="/datban/lands/thanhphohochiminh">Tp. Hồ Chí Minh</a>
	    <br/><br/>
	    <a href="#">Cần Thơ</a>
    </div>
{% endblock %}
	

templates/datban/m_lands.html
{% extends "datban/m_base.html" %}

{% load i18n %}
{% load humanize %}
{% load pagination_tags %}
{% block head_title %}Xem Đất Bán{% endblock %}

{% block leftbutton %}
	{% if not is_me %}
		<a id="homeButton" class="button" href="{% url profile_detail user %}">{% trans "My Lands" %}</a>
	{% else %}
		<a id="homeButton" class="button" href="{% url home %}">{% trans "Home" %}</a>
	{% endif %}	
	
{% endblock %}

{% block body %}
{% if lands %}
	{% autopaginate lands %}
    <ul id="albums" title="Albums" selected="true">
   	{% for land in lands %}
			<li>
				<a href="{{ land.full_map_url }}">
					<div class="landpreview">
						<img src="{{ land.static_map }}" width="160" height="160" alt="{% trans "Land Map" %}" class="mappreview"/>
					</div>
					<div class="landinfo">
						<ul>
							{% if land.is_private %}
								<li>
									<span class="private-button">Private</span>
								</li>
							{% endif %}
							<li>{% trans land.get_land_type_display %}</li>
							<li>{{ land.area }} m<sup>2</sup></li>
							<li>{% if land.price == 0 %}{% trans "Negotiable" %}{% else %}{{ land.price|intword }} Đồng{% endif %}</li>
							<li>
								{% if land.user.get_profile.name %}
			    					{{ land.user.get_profile.name }}
			    				{% else %}
			    					{{ land.user.username }}
			    				{% endif %}
			    			</li>
    						{% if land.owner_name %}
								<li>  
									{{ land.owner_name }}
								</li>
							{% endif %}
							<li>{{ land.get_listing_status_display }}</li>
							<li>{% trans "Contact: " %}{{ land.contact_name }} - {{ land.contact_phone }}</li>
						</ul>
					</div>
				</a>
				<div class="unit">{{ land.admin_unit.markup|safe }}</div>		 
			</li>
	{% endfor %}
		<li>
			{% paginate %}
		</li>
    </ul>
    
{% else %}
	<span> {% trans "There is no lands updated in this area." %}</span>
{% endif %}
{% endblock %}